"""add_users_table

Revision ID: b28fb3806145
Revises: 242aede75aae
Create Date: 2026-01-20 12:26:26.901995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28fb3806145'
down_revision: Union[str, Sequence[str], None] = '242aede75aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    
    # Seed initial admin user
    try:
        from app.config import get_settings
        from passlib.context import CryptContext
        
        settings = get_settings()
        # Use argon2 to avoid bcrypt compatibility issues
        pwd_context = CryptContext(schemes=["argon2"], deprecated="auto")
        
        hashed_password = pwd_context.hash(settings.admin_password)
        
        op.bulk_insert(table, [
            {
                'username': settings.admin_username,
                'password_hash': hashed_password
            }
        ])
    except ImportError:
        # Fallback if dependencies are missing during migration generation
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
